### ISSUE TITLE
[v0.2] Handle nest import in nest backend 

### ISSUE THREAD

**Issue by morales-gregorio** [INM-6/NetworkUnit#17]
Currently nest is imported in the backend even if just a model was initialized. This should be avoided, by limiting this import to just when NEST is actually needed.

**Comment by rgutzen** [comment]
Thanks for pointing that out. As you saw, this is due to the way the __init__.py files are constructed and also leads to some other weird problems when networkunit is imported within IPython or imported in sequence with other packages also depending on Nest. Thus, the __init__.py files should be reworked in general.

**Comment by morales-gregorio** [comment]
@rgutzen Fixed this in a real nice way!
