### ISSUE TITLE
correlation-test throws error 

### ISSUE THREAD

**Issue by Jojo-00** [INM-6/NetworkUnit#22]
While trying to calculate the pearson-correlation I got the following error message.

_Traceback (most recent call last):
  File "nu_test.py", line 96, in <module>
    test = PC_ks_test_class()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sciunit\tests.py", line 593, in init
    super(TestM2M, self).init(observation, name=name, **params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\networkunit\tests\test_correlation_test.py", line 37, in init
    self.params.update(params)
AttributeError: 'PC_ks_test_class' object has no attribute 'params'_

Where PC_ks_test_class derives sciunit.Test.M2M and correlation_dist_test. The same error occures when using correlation_matrix_test and correlation_test instead of correlation_dist_test. The score_type is scores.ks_distance.
Do any params have to be specified in this subclass?

**Comment by rgutzen** [comment]
The problem is that NetworkUnit does not yet use default parameters consistently, therefore it is required to define a `params` attribute in your derived test class that contains a dict with the parameters corresponding to the used test (see docstring).
It might also work to just specify an empty params dict, as there is for example a default value of `binsize=2*ms` specified in `correlation_test`.
Thank you for pointing this out, version 0.2 will have a more consistent way of handling default parameters.

**Comment by rgutzen** [comment]
linked to issue #15

**Comment by Jojo-00** [comment]
Thank you for the quick answer. After defining the params attribute the test-class worked well.
